pybo/views/answer_views.py
# views/answer_view.py
# create, modify, delete 메소드 포함


from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

# 'answer' 요청을 처리하는 blueprint 객체 bp
# 요청 뒤에 /answer 이 붙어있다면, 아래 블루프린트가 이를 받아 처리함.
bp = Blueprint('answer', __name__, url_prefix='/answer')


# 답변 생성 함수
# 사용자가 입력한 데이터를 담은 form 데이터를 받아서, DB INSERT 후 질문 상세 화면으로 이동

# 이 함수는, /create/question_id 형태의 요청을 POST 방식으로 처리
@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    # AnswerForm 객체 생성
    form = AnswerForm()

    # 해당 질문에 대한 정보를 DB 에서 받아옴
    question = Question.query.get_or_404(question_id)

    # 입력받은 form 에 대해, 데이터 검증한 결과가 참(즉, 입력한 데이터가 모두 조건에 맞는 경우)
    if form.validate_on_submit():
        # request 객체의 form 속성(dictionary 로 추정) 에서, 'content' 의 value 를 content 변수에 저장
        content = request.form['content']

        # Answer 객체 생성. Answer 테이블에서 요구하는 데이터를 채움
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)

        # question 객체에 답변들에 answer 객체를 append, 이에 따라 question <-> answer_set 쌍방 참조 가능
        question.answer_set.append(answer)
        db.session.commit()

        # 질문 상세 화면의 url 을 리턴
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id)
        )

    # 입력받은 form 에 대해, 데이터 검증 결과가 참이 아닌 경우(즉, 입력한 데이터 중 조건에 맞지 않는 것이 하나 이상 있는 경우)
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id)
            )
    else:
        form = AnswerForm(obj=answer)
    return render_template('question/answer_form.html', answer=answer, form=form)


@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/comment_views.py
# views/comment_views.py
# 질문과 답변 각각에 대한 댓글 등록, 수정, 삭재에 관한 view

from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import CommentForm
from pybo.models import Question, Comment, Answer
from pybo.views.auth_views import login_required


# 이 bp는 /comment 요청을 처리함
bp = Blueprint('comment', __name__, url_prefix='/comment')


# GET, POST 방식의 요청을 나누어 처리
# 질문에 댓글을 생성하는 함수
@bp.route('/create/question/<int:question_id>', methods=['GET', 'POST'])
@login_required
def create_question(question_id):
    # 댓글 form 객체 생성
    form = CommentForm()

    # 인자로 받은 question_id 를 통해 question 데이터를 저장
    question = Question.query.get_or_404(question_id)

    # 요청 방식이 POST 방식이고, form 의 데이터가 조건을 만족하는 경우
    if request.method == 'POST' and form.validate_on_submit():
        # comment 생성. 이때, user 필드에는 g.user, 즉 컨텍스트 변수인 g 가 가지고 있는 user 의 값을 저장하면 된다.
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), question=question)

        # 저장
        db.session.add(comment)
        db.session.commit()

        # anchor 적용.
        # 이를 해석해보면, '/detail/질문번호#comment_코멘트번호' 의 url 을 리턴.
        return redirect('{}#comment_{}'.format(
            url_for('question.detail', question_id=question_id), comment.id))

    # GET 방식인 경우, 댓글 등록 화면으로 이동
    return render_template('comment/comment_form.html', form=form)


# 댓글 수정 함수
@bp.route('/modify/question/<int:comment_id>', methods=['POST'])
@login_required
def modify_question(comment_id):
    # comment_id 를 key 로써 comment 를 가져옴
    comment = Comment.query.get_or_404(comment_id)

    # 컨텍스트 변수 g가 가진 user 와 comment.user 가 다른 경우, 질문 상세 화면으로 redirect
    if g.user != comment.user:
        flash('수정 권한이 없습니다')
        return redirect(url_for('question.detail', question_id=comment.question.id))

    # 요청 방식이 POST 인 경우
    if request.method == 'POST':
        # commentForm 객체 생성
        form = CommentForm()

        # 입력 데이터가 조건에 맞는 경우
        if form.validate_on_submit():
            # comment 를 객체화?
            form.populate_obj(comment)

            # comment 의 수정 일자를 현재 시각으로 update
            comment.modify_date = datetime.now()

            # 저장
            db.session.commit()

            # 질문 상세 화면의 해당 댓글로 설정된 anchor 로 리턴
            return redirect(
                '{}#comment_{}'.format(url_for('question.detail', question_id=comment.question.id), comment_id)
            )
    # 요청 방식이 GET 방식인 경우
    else:
        # form 에 comment 객체를 저장
        form = CommentForm(obj=comment)

    # 댓글 입력 화면으로 이동
    return render_template('comment/comment_form.html', form=form)


# 댓글 삭제 함수
@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
    # comment_id 를 바탕으로, 해당 comment 를 불러옴
    comment = Comment.query.get_or_404(comment_id)

    # question_id 에 comment 데이터가 참조하는 question 데이터의 id 값을 저장
    question_id = comment.question.id

    # 컨텍스트 변수 g 의 user 데이터와 현재 작성 user 데이터가 다른 경우
    if g.user != comment.user:
        flash('삭제 권한이 없습니다')
        # 질문 상세 화면으로 이동
        return redirect(url_for('question.detail', question_id=question_id))

    # 저장
    db.session.delete(comment)
    db.session.commit()

    # 질문 상세 화면으로 이동
    return redirect(url_for('question.detail', question_id=question_id))


# 답변 댓글 등록 함수
@bp.route('/create/answer/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def create_answer(answer_id):
    # 댓글 등록 form 객체 생성
    form = CommentForm()

    # answer_id 를 바탕으로 answer 객체를 불러옴
    answer = Answer.query.get_or_404(answer_id)

    # 요청 방식이 POST 이고 입력 데이터가 조건을 만족한다면
    if request.method == 'POST' and form.validate_on_submit():
        # comment 객체 생성
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), answer=answer)

        # 저장
        db.session.add(comment)
        db.session.commit()

        # anchor 기능 적용된 질문상세 화면 url 을 리턴
        return redirect('{}#comment_{}'.format(
            url_for('question.detail', question_id=answer.question.id), comment.id))

    # 댓글 등록 화면으로 이동
    return render_template('comment/comment_form.html', form=form)


# 답변 댓글 수정 함수
@bp.route('/modify/answer/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_answer(comment_id):
    # comment_id 를 바탕으로 comment 객체를 불러옴
    comment = Comment.query.get_or_404(comment_id)

    # 컨텍스트 변수의 user 데이터와 댓글 작성 user 데이터의 값이 다른 경우
    if g.user != comment.user:
        flash('수정 권한이 없습니다')

        # 질문 상세 화면으로 이동
        return redirect(url_for('question.detail', question_id=comment.answer.id))

    # 요청 메소드가 POST 인 경우
    if request.method == 'POST':
        # form 객체 생성
        form = CommentForm()

        # form 데이터가 조건을 만족하는 경우
        if form.validate_on_submit():
            # comment 를 객체화?
            form.populate_obj(comment)

            # comment 수정일자 update
            comment.modify_date = datetime.now()

            # 저장
            db.session.commit()

            # anchor 적용된 질문 상세 화면으로 이동
            return redirect('{}#comment_{}'.format(
                url_for('question.detail', question_id=comment.answer.question.id), comment.id))

    # 요청 방식이 GET 인 경우
    else:
        # form 변수에 comment 를 객체화
        form = CommentForm(obj=comment)

    # 댓글 등록 화면으로 이동
    return render_template('comment/comment_form.html', form=form)


# 답변 댓글 삭제 함수
@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
    # comment_id 를 바탕으로 댓글 데이터 가져옴
    comment = Comment.query.get_or_404(comment_id)

    # question_id 변수에 comment 데이터가 참조하는 answer 데이터가 참조하는 question 데이터의 id 를 가져옴
    question_id = comment.answer.question.id

    # 컨텍스트 변수 g 의 user 데이터와 comment 작성 user 의 데이터가 다른 경우
    if g.user != comment.user:
        flash('삭제 권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))

    # 해당 comment 삭제
    db.session.delete(comment)
    db.session.commit()

    # 질문 상세 화면으로 이동
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
# views/question_views.py
# _nullast, _list, detail, create, modify, delete 메소드 포함

from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash, current_app
from werkzeug.utils import redirect
from sqlalchemy import func, nullslast

from pybo import db

from pybo.forms import QuestionForm, AnswerForm

from pybo.models import Question, question_voter, Answer, User

from pybo.views.auth_views import login_required


bp = Blueprint('question', __name__, url_prefix='/question')


# sqlite DB 에 대한 처리.
def _nullslast(obj):
    if current_app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        return obj
    else:
        return nullslast(obj)


# /question/list 요청을 처리하는 함수
@bp.route('/list/')
def _list():
    # paging
    page = request.args.get('page', type=int, default=1)

    # request 객체에 담긴 검색 키워드
    kw = request.args.get('kw', type=str, default='')

    # request 객체에 담긴 정렬 기준
    so = request.args.get('so', type=str, default='recent')

    # 추천 순 정렬인 경우
    if so == 'recommend':
        sub_query = db.session.query(question_voter.c.question_id, func.count('*').label('num_voter'))\
            .group_by(question_voter.c.question_id).subquery()

        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(_nullslast(sub_query.c.num_voter.desc()), Question.create_date.desc())

    # 인기 순 정렬인 경우
    elif so == 'popular':
        sub_query = db.session.query(Answer.question_id, func.count('*').label('num_answer')) \
            .group_by(Answer.question_id).subquery()

        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(_nullslast(sub_query.c.num_answer.desc()), Question.create_date.desc())

    # 그 이외 경우
    else:
        question_list = Question.query.order_by(Question.create_date.desc())

    # 검색 키워드가 있는 경우
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()

        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |
                    Question.content.ilike(search) |
                    User.username.ilike(search) |
                    sub_query.c.content.ilike(search) |
                    sub_query.c.username.ilike(search)
                    ) \
            .distinct()

    question_list = question_list.paginate(page, per_page=10)

    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw, so=so)


# 질문 상세 조회 화면
@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)


# 질문 생성 화면
# GET 요청(질문 등록 화면으로 이동)과 POST 요청(질문 데이터 db 저장)을 나눠서 처리
@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionForm()

    # 요청방식 POST && form 데이터 조건 만족하는 경우
    if request.method == 'POST' and form.validate_on_submit():
        # DB 저장
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main.index'))

    return render_template('question/question_form.html', form=form)


# 질문 수정 함수
# GET 요청(수정 화면으로 이동)과 POST 요청(수정 내역 저장)을 따로 처리
@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    # 컨텍스트 변수 g 에 담긴 user 데이터와 질문 작성자 data 가 다른 경우
    if g.user != question.user:
        flash('수정 권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))

    # 질문 수정하고 저장하기 버튼 누른 경우 -> post 방식 요청
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            # form 을 객체화
            form.populate_obj(question)

            # 수정일자 update
            question.modify_date = datetime.now()

            # commit
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))

    # 질문 수정 버튼을 누르는 경우 -> get 방식의 요청
    else:
        form = QuestionForm(obj=question)
        return render_template('question/question_form.html', form=form)


# 질문 삭제 함수
@bp.route('/delete/int:<question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제 권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()

    return redirect(url_for('question._list'))

pybo/views/vote_views.py
# views/vote_views.py
# 추천 관련 함수인 question, answer 함수를 가짐

from flask import Blueprint, url_for, flash, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

# /vote url 을 처리하는 bp
bp = Blueprint('vote', __name__, url_prefix='/vote')


# /vote/question/q_id 를 처리하는 함수
@bp.route('/question/<int:question_id>/')
@login_required
def question(question_id):
    # question id 를 통해 해당 질문 데이터를 가져온다.
    _question = Question.query.get_or_404(question_id)

    # 컨텍스트 변수 g 의 user 데이터와 질문 작성자 데이터가 같은 경우, 추천 불가
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할 수 없습니다')

    # 해당 질문 객체의 voter 에 현재 사용자 데이터를 추가
    else:
        _question.voter.append(g.user)
        db.session.commit()

    return redirect(url_for('question.detail', question_id=question_id))


# vote/answer/answer_id url 을 처리하는 함수
@bp.route('/answer/<int:answer_id>/')
@login_required
def answer(answer_id):
    # answer_id 를 통해 답변 데이터를 가져옴
    _answer = Answer.query.get_or_404(answer_id)

    # 현재 사용자와 작성자가 같다면 추천 불가
    if g.user == _answer.user:
        flash('본인이 작성한 답변은 추천할 수 없습니다')

    # 아닌 경우
    else:
        # 해당 답변 데이터의 voter 에 현재 사용자 추가
        _answer.voter.append(g.user)

        # 저장
        db.session.commit()

    return redirect(url_for('question.detail', question_id=_answer.question.id))

pybo/templates/question/answer_form.html
<!-- 답변 입력 화면 -->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 답변 입력 form 시작 -->
    <form method="post" class="post-form">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
    <!-- 답변 입력 form 끝 -->

</div>
{% endblock %}

pybo/templates/question/question_detail.html
<!-- 질문 상세 조회 화면 -->

{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <!-- 추천 영역 시작 -->
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ question.voter|length }}</div>
            <a href="#" data-uri="{{ url_for('vote.question', question_id=question.id) }}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <!-- 추천 영역 끝 -->

        <!-- 질문영역 시작 -->
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ question.content|markdown }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date|datetime }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.user.username }}</div>
                            <div>{{ question.create_date|datetime }}</div>
                        </div>
                    </div>
                    <!-- 로그인한 유저가 작성자라면 수정, 삭제 가능 시작-->
                    {% if g.user == question.user %}
                    <div class="my-3">
                        <a href="{{ url_for('question.modify', question_id=question.id) }}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 로그인한 유저가 작성자라면 수정, 삭제 가능 끝-->

                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.user.username }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{ url_for('comment.modify_question', comment_id=comment.id) }}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{{ url_for('comment.delete_question', comment_id=comment.id) }}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{ url_for('comment.create_question', question_id=question.id) }}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter|length }}</div>
            <a href="#" data-uri="{{ url_for('vote.answer', answer_id=answer.id) }}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content|markdown }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date|datetime }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.user.username }}</div>
                            <div>{{ answer.create_date|datetime }}</div>
                        </div>
                    </div>
                    {% if g.user == answer.user %}
                    <div class="my-3">
                        <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                            data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 답변 댓글 Start -->
                    {% if answer.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.user.username }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{ url_for('comment.modify_answer', comment_id=comment.id) }}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{{ url_for('comment.delete_answer', comment_id=comment.id) }}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{ url_for('comment.create_answer', answer_id=answer.id) }}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 답변 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>

    <!-- 질문 등록 form 시작 -->
    <form method="post" class="post-form my-3">

        {{ form.csrf_token }}

        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or ''}}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10"> {{form.content.data or ''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
    <!-- 질문 등록 form 끝 -->

</div>
{% endblock %}